YEAR: 2025

# TERRITORIOS DISPONIBLES: AND, ARA, AST, BAL, CAN, CAT, CLM, CYL, EUS, GAL, LRI, MAD, MUR, NAV, VAL
# DEJAR VACÍO PARA GENERAR TODOS LOS TERRITORIOS
TERRITORIOS: AND

# IDIOMAS DISPONIBLES: CAS, CAT, EUS, GAL
# DEJAR VACÍO PARA GENERAR TODOS LOS IDIOMAS (SEGÚN TERRITORIO)
IDIOMAS:

# Ubicación de pngquant
PNGQUANT_PATH: /usr/bin/pngquant